### ISSUE TITLE
Access Forbidden On Initial Run

### ISSUE THREAD

**Issue by eddingtonm** [ushainformatique/usniframework#1]
Hi, I want to view how you created the framework but I get a Access Forbidden...."You don't have permission to access the requested directory. There is either no index document or the directory is read-protected." error when I run it from my localhost. 

How do I configure it to redirect me to the installation page or demo page? I just ran "localhost/usniframework/"
Thank you.

**Comment by ushainformatique** [comment]
Hello, You could not run it directly. You have to install WhatACart to check how it is working.
